#ifndef ENUM_ITEM_H
#define ENUM_ITEM_H

#include <cstdint>

namespace core::enums {

enum class Item : uint8_t {
    //// region Material
    BatWing,
    Bottle,
    Coal,
    Cotton,
    CottonYarn,
    CottonCloth,
    CopperOre,
    CopperIngot,
    Claw,
    Dust,
    Ear,
    Fang,
    Feather,
    Horn,
    IronOre,
    IronIngot,
    Leather,
    Log,
    Pelt,
    Sand,
    Scale,
    Stone,
    Web,
    WebYarn,
    /// region Jewel
    Amethyst,
    Amber,
    Diamond,
    Emerald,
    Opal,
    Rubi,
    Saphir,
    Topaz,
    /// region Rune
    Eihwaz,
    Gebo,
    Hagalaz,
    Jera,
    Nauthiz,
    Perdhro,
    Raidho,
    Ansuz,
    Tiwaz,
    Algiz,
    Berkana,
    Dagaz,
    Inguz,
    Laguz,
    Mannaz,
    Othila,
    /// region Key
    DungeonKey,
    ArenaSymbol,
    /// region Potion
    HealthPotion,
    ManaPotion,
    Elixir,
    /// region CLOTH EQUIPMENTS
    MageHat,
    Robe,
    Shoes,
    TopHat,
    Coat,
    LightShoes,
    LightCloak,
    /// region LEATHER EQUIPMENTS
    Hood,
    LeatherArmor,
    LeatherBoots,
    LightHelmet,
    ShoulderArmor,
    Boots,
    LeatherCloak,
    /// region METAL EQUIPMENTS
    WarriorHelmet,
    WarlordArmor,
    WarlordBoots,
    WarlordHelmet,
    WarriorArmor,
    WarriorBoots,
    /// region LEFT HAND
    CastleShield,
    Ankh,
    Lyre,
    Flute,
    Lute,
    Claws,
    Quiver,
    Knife,
    Orb,
    Spellbook,
    /// region RIGHT HAND
    WarAxe,
    ShortBow,
    Crossbow,
    AssassinDagger,
    CeremonialDagger,
    Gloves,
    HuntingSpear,
    BrightSword,
    CrystalWand,
    LunarStaff,
    OrbWand,
    SharpAxe,
    WarTrident,
    MidnightScythe,
    WarHammer,
    ShortMace,
    Club,
    /// region RINGS
    NeutralRing,
    PowerRing,
    SkullRing,
    NecroRing,
    /// region NECKLACES
    FeatherNecklace,
    FangNecklace,
    ClawNecklace,
    PowerNecklace,
};
}
#endif
